# Change these first
owner: yjl9903 # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: Home
    url: https://onekuma.cn
    icon: https://onekuma.cn/favicon.svg
  - name: Blog
    url: https://blog.onekuma.cn
  - name: Hexo
    url: https://xlor.cn
  - name: Anime Garden
    url: https://garden.breadio.wiki
    icon: https://garden.breadio.wiki/favicon.svg
  - name: Anime Garden API
    url: https://garden.breadio.wiki/api
    icon: https://garden.breadio.wiki/favicon.svg
  - name: Anime Garden - Test
    url: https://test.animes.garden
    icon: https://test.animes.garden/favicon.svg
    headers:
      - 'User-Agent: animegarden@v0.1.0'
  - name: Anime Garden API - Test
    url: https://test.animes.garden/api
    headers:
      - 'User-Agent: animegarden@v0.1.0'
    icon: https://test.animes.garden/favicon.svg
  - name: KeepShare
    url: https://keepshare.org/gv78k1oi/magnet%3A%3Fxt%3Durn%3Abtih%3AULRHXZU7IHGEIVKIXMRIGSRHSY26K7TF
    icon: https://keepshare.org/img/logo.svg
  # - name: 雷索纳斯市场
  #   slug: resonance-market
  #   url: https://resonance.breadio.wiki/
  #   icon: https://resonance.breadio.wiki/favicon.png
  #   headers:
  #     - "User-Agent: resonance-market"
  - name: Livehouse
    url: https://live.onekuma.cn/
    icon: https://live.onekuma.cn/favicon.jpg
  - name: 弥希 Miki 舰长日报
    url: https://miki.xlor.cn/
    icon: https://miki.xlor.cn/favicon.jpeg

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.onekuma.cn
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
# user-agent: yjl9903
